apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cicd-demo
  labels:
    app: nginx-cicd-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-cicd-demo
  template:
    metadata:
      labels:
        app: nginx-cicd-demo
    spec:
      containers:
      # Основной контейнер - Nginx
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
        - name: nginx-html
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 5
      
      # Sidecar контейнер - Metrics Server
      - name: metrics-server
        image: python:3.9-alpine
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: metrics-script
          mountPath: /app/scripts
        workingDir: /app/scripts
        command: ["/bin/sh"]
        args: ["-c", "pip install requests && python metrics-server.py"]
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
      
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: nginx-html
        configMap:
          name: nginx-html
      - name: metrics-script
        configMap:
          name: metrics-script