apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-cicd-demo
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: clerikc.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-cicd-demo
            port:
              number: 80