name: 🔍 Test Ingress Controller

on:
  workflow_dispatch:  # Это позволяет запускать вручную из UI GitHub
  push:
    tags:
      - 'v-*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4
      
    - name: 🔧 Setup kubectl
      uses: azure/setup-kubectl@v3

    - name: 🔐 Load Kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > /tmp/kubeconfig.yaml
        export KUBECONFIG=/tmp/kubeconfig.yaml
        kubectl get nodes

    - name: 🔍 Проверить Ingress Controller
      run: |
        export KUBECONFIG=/tmp/kubeconfig.yaml
        
        echo "=== 1. Проверяем Ingress Controller ==="
        kubectl get service -n ingress-nginx
        
        echo "=== 2. Ждем получения внешнего IP ==="
        timeout 180s bash -c 'while [[ $(kubectl get service -n ingress-nginx ingress-nginx-controller -o jsonpath="{.status.loadBalancer.ingress[0].ip}") == "" ]]; do sleep 5; echo "Ожидаем External IP..."; done'
        
        EXTERNAL_IP=$(kubectl get service -n ingress-nginx ingress-nginx-controller -o jsonpath="{.status.loadBalancer.ingress[0].ip}")
        echo "✅ External IP: $EXTERNAL_IP"
        
        echo "=== 3. Проверяем HTTP доступность ==="
        curl -f http://$EXTERNAL_IP || echo "❌ HTTP не работает"