name: 🔍 Test Ingress Access

on:
  workflow_dispatch:
  push:
    tags:
      - 'v-*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4
      
    - name: 🔧 Setup kubectl
      uses: azure/setup-kubectl@v3

    - name: 🔐 Load Kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > /tmp/kubeconfig.yaml
        export KUBECONFIG=/tmp/kubeconfig.yaml
        kubectl get nodes

    - name: 🏗️ Deploy Infrastructure
      run: |
        export KUBECONFIG=/tmp/kubeconfig.yaml
        echo "=== Deploying Infrastructure ==="
        kubectl apply -f k8s/infrastructure/ingress-controller.yaml
        sleep 10

    - name: 🛠️ Deploy Test Application
      run: |
        export KUBECONFIG=/tmp/kubeconfig.yaml
        
        echo "=== Deploying Test Application ==="
        kubectl create configmap nginx-html --from-file=html/index.html -o yaml --dry-run=client | kubectl apply -f -
        kubectl create configmap nginx-config --from-file=nginx-config/nginx.conf -o yaml --dry-run=client | kubectl apply -f -
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        
        echo "⏳ Waiting for application..."
        sleep 20

    - name: 🔍 Проверить Ingress Controller
      run: |
        export KUBECONFIG=/tmp/kubeconfig.yaml
        
        echo "=== 1. Проверяем Ingress Controller ==="
        kubectl get service -n ingress-nginx
        
        echo "=== 2. Используем внешний IP сервера ==="
        SERVER_IP="185.8.22.53"
        echo "Тестируем на IP: $SERVER_IP"
        
        echo "=== 3. Проверяем HTTP через порт 80 ==="
        curl -f http://$SERVER_IP:80 && echo "✅ HTTP на порту 80 РАБОТАЕТ!" || echo "❌ HTTP на порту 80 не работает"
        
        echo "=== 4. Проверяем с Host header ==="
        curl -f -H "Host: clerikc.ru" http://$SERVER_IP:80 && echo "✅ HTTP с Host header РАБОТАЕТ!" || echo "❌ HTTP с Host header не работает"
        
        echo "=== 5. Проверяем текущие порты 30080/30443 ==="
        curl -f http://$SERVER_IP:30080 && echo "✅ HTTP на 30080 РАБОТАЕТ!" || echo "❌ HTTP на 30080 не работает"

    - name: 🔍 Debug if Failed
      if: failure()
      run: |
        export KUBECONFIG=/tmp/kubeconfig.yaml
        echo "=== ДЕТАЛЬНАЯ ДИАГНОСТИКА ==="
        kubectl describe service -n ingress-nginx
        kubectl logs -n ingress-nginx -l app.kubernetes.io/name=ingress-nginx --tail=20
        kubectl get ingress -A