name: 🔍 Test Ingress Access

on:
  workflow_dispatch:
  push:
    tags:
      - 'fixed-*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4
      
    - name: 🔧 Setup kubectl
      uses: azure/setup-kubectl@v3

    - name: 🔐 Load Kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > /tmp/kubeconfig.yaml
        export KUBECONFIG=/tmp/kubeconfig.yaml
        kubectl get nodes

    - name: 🗑️ Очистить старые ресурсы
      run: |
        export KUBECONFIG=/tmp/kubeconfig.yaml
        echo "=== Очищаем старые ресурсы ==="
        kubectl delete namespace ingress-nginx --ignore-not-found=true
        kubectl delete namespace cert-manager --ignore-not-found=true
        sleep 10

    - name: 🚀 Установить Official Ingress Controller
      run: |
        export KUBECONFIG=/tmp/kubeconfig.yaml
        
        echo "=== 1. Устанавливаем официальный ingress-nginx ==="
        kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
        
        echo "=== 2. Ждем запуска ingress controller ==="
        sleep 30
        
        echo "=== 3. Проверяем статус ==="
        kubectl get pods -n ingress-nginx
        kubectl get service -n ingress-nginx
        
        echo "=== 4. Ждем готовности ==="
        kubectl wait --namespace ingress-nginx \
          --for=condition=ready pod \
          --selector=app.kubernetes.io/component=controller \
          --timeout=120s

    - name: 🔧 Исправить порты для Kind
      run: |
        export KUBECONFIG=/tmp/kubeconfig.yaml
        
        echo "=== Исправляем сервис на NodePort с правильными портами ==="
        kubectl patch service -n ingress-nginx ingress-nginx-controller --type='json' -p='[
          {"op": "replace", "path": "/spec/type", "value": "NodePort"},
          {"op": "replace", "path": "/spec/ports/0/nodePort", "value": 30080},
          {"op": "replace", "path": "/spec/ports/1/nodePort", "value": 30443}
        ]'
        
        echo "=== Проверяем исправленный сервис ==="
        kubectl get service -n ingress-nginx

    - name: 🛠️ Deploy Test Application
      run: |
        export KUBECONFIG=/tmp/kubeconfig.yaml
        
        echo "=== Deploying Test Application ==="
        kubectl create configmap nginx-html --from-file=html/index.html -o yaml --dry-run=client | kubectl apply -f -
        kubectl create configmap nginx-config --from-file=nginx-config/nginx.conf -o yaml --dry-run=client | kubectl apply -f -
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        
        echo "⏳ Waiting for application..."
        sleep 20

    - name: 🌐 Настроить Ingress
      run: |
        export KUBECONFIG=/tmp/kubeconfig.yaml
        
        echo "=== Применяем Ingress из файла ==="
        kubectl apply -f k8s/infrastructure/ingress.yaml
        
        echo "=== Проверяем Ingress ==="
        kubectl get ingress

    - name: 🔍 Полная диагностика ingress
      run: |
        export KUBECONFIG=/tmp/kubeconfig.yaml
        
        echo "=== 1. Проверяем все ресурсы ==="
        kubectl get pods -A
        kubectl get services -A
        kubectl get ingress -A
        
        echo "=== 2. Детальная проверка ingress-nginx ==="
        kubectl describe pod -n ingress-nginx -l app.kubernetes.io/component=controller
        kubectl logs -n ingress-nginx -l app.kubernetes.io/component=controller --tail=20
        
        echo "=== 3. Проверяем приложение ==="
        kubectl get pods -l app=nginx-cicd-demo
        kubectl logs -l app=nginx-cicd-demo --tail=5
        
        echo "=== 4. Проверяем сервис приложения ==="
        kubectl get service nginx-cicd-demo
        
        echo "=== 5. Тестируем ВНУТРИ кластера ==="
        kubectl run test-curl --image=curlimages/curl --rm -i --restart=Never --command -- \
          sh -c 'echo "=== Тест сервиса ===" && \
                 curl -f http://nginx-cicd-demo.default.svc.cluster.local && echo "✅ Сервис работает" && \
                 echo "=== Тест ingress ===" && \
                 curl -f -H "Host: clerikc.ru" http://ingress-nginx-controller.ingress-nginx.svc.cluster.local && echo "✅ Ingress работает внутри кластера"'

    - name: 🌐 Тестируем внешний доступ
      run: |
        export KUBECONFIG=/tmp/kubeconfig.yaml
        SERVER_IP="185.8.22.53"
        
        echo "=== Тестируем доступность снаружи ==="
        echo "=== Порт 80 (проброшен на 30080) ==="
        curl -v --connect-timeout 10 -H "Host: clerikc.ru" http://$SERVER_IP:80/ && echo "✅ Ingress работает через порт 80!" || echo "❌ Порт 80 не отвечает"
        
        echo "=== Прямой NodePort 30080 ==="
        curl -v --connect-timeout 10 -H "Host: clerikc.ru" http://$SERVER_IP:30080/ && echo "✅ Ingress работает через NodePort 30080!" || echo "❌ NodePort 30080 не отвечает"

    - name: 🔍 Debug if Failed
      if: failure()
      run: |
        export KUBECONFIG=/tmp/kubeconfig.yaml
        echo "=== ДЕТАЛЬНАЯ ДИАГНОСТИКА ==="
        kubectl describe service -n ingress-nginx
        kubectl logs -n ingress-nginx -l app.kubernetes.io/component=controller --tail=30
        kubectl get ingress -A
        kubectl describe ingress nginx-cicd-demo